export enum MODELS {
  ADMIN = `ADMIN`,
  USER = `USER`,
  TAG = `TAG`,
  SKILL = `SKILL`,



  /** base models */
  ANALYTIC = `ANALYTIC`,
  MENTION = `MENTION`,
  REACTION = `REACTION`,
  RATING = `RATING`,
  COMMENT = `COMMENT`,
  REPLY = `REPLY`,
  CONTENT_SKILL = `CONTENT_SKILL`,
  PHOTO = `PHOTO`,
  VIDEO = `VIDEO`,
  AUDIO = `AUDIO`,
  FIELD = `FIELD`,
  ACTION_REQUEST = `ACTION_REQUEST`,
  FOLLOW = `FOLLOW`,
  /** end base models */



  NOTICE = `NOTICE`,
  INTERVIEW = `INTERVIEW`,
  INTERVIEWER = `INTERVIEWER`,
  INTERVIEWEE = `INTERVIEWEE`,
  QUESTION = `QUESTION`,
  ANSWER = `ANSWER`,
}








export enum AVENGER_EVENT_TYPES {
  NEW_RATING = `NEW_RATING`,
  NEW_SKILL_RATING = `NEW_SKILL_RATING`,
  NEW_SKILL_SUBMITTED = `NEW_SKILL_SUBMITTED`,
  NEW_SKILL_RECEIVED = `NEW_SKILL_RECEIVED`,

  NEW_ANALYTIC = `NEW_ANALYTIC`,

  // notice
  NOTICE_MENTION = `NOTICE_MENTION`,
  NEW_NOTICE_REACTION = `NEW_NOTICE_REACTION`,
  NOTICE_REACTION_RESCINDED = `NOTICE_REACTION_RESCINDED`,
  NOTICE_UPDATED = `NOTICE_UPDATED`,
  NOTICE_DELETED = `NOTICE_DELETED`,
  NOTICE_SHARED = `NOTICE_SHARED`,
  NOTICE_UNSHARED = `NOTICE_UNSHARED`,
  NOTICE_QUOTED = `NOTICE_QUOTED`,
  NEW_NOTICE_REPLY = `NEW_NOTICE_REPLY`,

  // interview
  INTERVIEW_MENTION = `INTERVIEW_MENTION`,
  NEW_INTERVIEW_REACTION = `NEW_INTERVIEW_REACTION`,
  INTERVIEW_REACTION_RESCINDED = `INTERVIEW_REACTION_RESCINDED`,
  INTERVIEW_UPDATED = `INTERVIEW_UPDATED`,
  INTERVIEW_DELETED = `INTERVIEW_DELETED`,
  NEW_INTERVIEW_COMMENT = `NEW_INTERVIEW_COMMENT`,
  NEW_INTERVIEW_COMMENT_REACTION = `NEW_INTERVIEW_COMMENT_REACTION`,
  NEW_INTERVIEW_COMMENT_REPLY = `NEW_INTERVIEW_COMMENT_REPLY`,
  NEW_INTERVIEW_COMMENT_REPLY_REACTION = `NEW_INTERVIEW_COMMENT_REPLY_REACTION`,
  REACTION_RESCINDED = "REACTION_RESCINDED",
  NEW_REACTION = "NEW_REACTION",
  DELETED = "DELETED",
  UPDATED = "UPDATED",
  MENTION = "MENTION",
  NEW_COMMENT = "NEW_COMMENT",
  NEW_COMMENT_REPLY = "NEW_COMMENT_REPLY",
  INTERVIEWER_RATING = "INTERVIEWER_RATING",
  INTERVIEWEE_RATING = "INTERVIEWEE_RATING"
}

export enum ANALYTIC_EVENTS {
  SEEN = `SEEN`,
  DETAILS_EXPANDED = `DETAILS_EXPANDED`,
}

export enum NOTICE_STAT {
  REPLIES_COUNT = 'REPLIES_COUNT',
  QUOTES_COUNT = 'QUOTES_COUNT',
  SHARES_COUNT = 'SHARES_COUNT',
  SEEN_COUNT = 'SEEN_COUNT',
  DETAILS_EXPANDED_COUNT = 'DETAILS_EXPANDED_COUNT',
}




export enum INTERVIEW_STAT {
  SEEN_COUNT = 'SEEN_COUNT',
  DETAILS_EXPANDED_COUNT = 'DETAILS_EXPANDED_COUNT',
  INTERVIEWER_RATING = "INTERVIEWER_RATING",
  INTERVIEWEE_RATING = "INTERVIEWEE_RATING"
}


export enum AVENGER_NOTIFICATION_TARGET_TYPES {
  NOTICE = 'NOTICE'
}



export enum AVENGER_ADMIN_ROLES {
  ADMINISTRATOR = 'ADMINISTRATOR',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
}



export enum AVENGER_SKILL_STATUS {
  ACTIVE = `ACTIVE`,
}


export enum INTERVIEW_VIEW_STATE {
  OPEN = `OPEN`,
  ARCHIVED = `ARCHIVED`,
}



export enum COMMON_SOCKET_EVENT_TYPES {
  // socket actions
  SOCKET_TRACK = 'SOCKET_TRACK',
  SOCKET_UNTRACK = 'SOCKET_UNTRACK',
  SOCKET_TO_USER_EVENT = 'SOCKET_TO_USER_EVENT',
  SOCKET_JOIN_ROOM = 'SOCKET_JOIN_ROOM',
  SOCKET_LEAVE_ROOM = 'SOCKET_LEAVE_ROOM',

  // events
  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_MESSAGING = 'NEW_MESSAGING',
  MESSAGING_EVENTS_SUBSCRIBED = 'MESSAGING_EVENTS_SUBSCRIBED',
  MESSAGING_EVENTS_UNSUBSCRIBED = 'MESSAGING_EVENTS_UNSUBSCRIBED',
  TO_MESSAGING_ROOM = 'TO_MESSAGING_ROOM',
  JOIN_TO_MESSAGING_ROOM = 'JOIN_TO_MESSAGING_ROOM',
  LEAVE_TO_MESSAGING_ROOM = 'LEAVE_TO_MESSAGING_ROOM',
  MESSAGE_TYPING = 'MESSAGE_TYPING',
  MESSAGE_TYPING_STOPPED = 'MESSAGE_TYPING_STOPPED',
  
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_UNFOLLOWER = 'NEW_UNFOLLOWER',
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  NEW_CONVERSATION_MESSAGE = 'NEW_CONVERSATION_MESSAGE',
  CONVERSATION_MEMBER_ADDED = 'CONVERSATION_MEMBER_ADDED',
  CONVERSATION_MEMBER_REMOVED = 'CONVERSATION_MEMBER_REMOVED',
  CONVERSATION_MEMBER_LEFT = 'CONVERSATION_MEMBER_LEFT',
  CONVERSATION_EVENTS_SUBSCRIBED = 'CONVERSATION_EVENTS_SUBSCRIBED',
  CONVERSATION_EVENTS_UNSUBSCRIBED = 'CONVERSATION_EVENTS_UNSUBSCRIBED',
  CONVERSATION_MESSAGE_TYPING = 'CONVERSATION_MESSAGE_TYPING',
  CONVERSATION_MESSAGE_TYPING_STOPPED = 'CONVERSATION_MESSAGE_TYPING_STOPPED',
  CONVERSATION_UPDATED = 'CONVERSATION_UPDATED',
  CONVERSATION_DELETED = 'CONVERSATION_DELETED',
}